services:
  - name: llm-backend
    type: web  # Must be 'web' not 'worker'
    env: python
    plan: free
    build:
      path: ./backend
      dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: 8000  # Default port if not set otherwise
      - key: ASSEMBLYAI_API_KEY
        fromGroup: llm-secrets
      - key: GROQ_API_KEY
        fromGroup: llm-secrets
      - key: HUGGINGFACE_API_TOKEN
        fromGroup: llm-secrets

  - name: llm-frontend
    type: web
    runtime: python
    build:
      path: ./frontend
      dockerfile: Dockerfile
    env: python
    envVars:
      - key: BACKEND_URL
        value: https://llm-backend.onrender.com
